/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cursoemvideo.olamundo;

/**
 *
 * @author lalan
 */
public class OlaMundoJava extends javax.swing.JFrame {

    /**
     * Creates new form OlaMundoJava
     */
    public OlaMundoJava() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensagem = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        cbmMensage = new javax.swing.JButton();
        CmgMensage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMensagem.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        lblMensagem.setText("Oçê Me Ama?");

        btnClick.setBackground(new java.awt.Color(204, 204, 204));
        btnClick.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnClick.setForeground(new java.awt.Color(255, 0, 255));
        btnClick.setText("Sim!");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        cbmMensage.setBackground(new java.awt.Color(204, 204, 204));
        cbmMensage.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cbmMensage.setForeground(new java.awt.Color(255, 0, 255));
        cbmMensage.setText("NÃO!");
        cbmMensage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmMensageActionPerformed(evt);
            }
        });

        CmgMensage.setBackground(new java.awt.Color(204, 204, 204));
        CmgMensage.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        CmgMensage.setForeground(new java.awt.Color(255, 0, 204));
        CmgMensage.setText("Sem Duvidas");
        CmgMensage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmgMensageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnClick)
                .addGap(521, 521, 521)
                .addComponent(CmgMensage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 599, Short.MAX_VALUE)
                .addComponent(cbmMensage)
                .addGap(180, 180, 180))
            .addGroup(layout.createSequentialGroup()
                .addGap(455, 455, 455)
                .addComponent(lblMensagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClick)
                            .addComponent(cbmMensage))
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CmgMensage)
                        .addGap(80, 80, 80))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        // TODO add your handling code here:
        lblMensagem.setText("Sempre Soube disso!"
                + "Eu sou Demais");
    }//GEN-LAST:event_btnClickActionPerformed

    private void cbmMensageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmMensageActionPerformed
        // TODO add your handling code here:
        lblMensagem.setText("Mentirosa, Ama sim!");
    }//GEN-LAST:event_cbmMensageActionPerformed

    private void CmgMensageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmgMensageActionPerformed
        // TODO add your handling code here:
        lblMensagem.setText("Pai Deixa Novinha doida");
            
    }//GEN-LAST:event_CmgMensageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OlaMundoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OlaMundoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OlaMundoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OlaMundoJava.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OlaMundoJava().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CmgMensage;
    private javax.swing.JButton btnClick;
    private javax.swing.JButton cbmMensage;
    private javax.swing.JLabel lblMensagem;
    // End of variables declaration//GEN-END:variables
}
